// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Browse.Categories;
using Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists;
using Soenneker.Spotify.OpenApiClient.Browse.NewReleases;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Spotify.OpenApiClient.Browse
{
    /// <summary>
    /// Builds and executes requests for operations under \browse
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BrowseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The categories property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Browse.Categories.CategoriesRequestBuilder Categories
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Browse.Categories.CategoriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The featuredPlaylists property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder FeaturedPlaylists
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The newReleases property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Browse.NewReleases.NewReleasesRequestBuilder NewReleases
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Browse.NewReleases.NewReleasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Browse.BrowseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BrowseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/browse", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Browse.BrowseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BrowseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/browse", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
