// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Me.Following
{
    /// <summary>The ID type: currently only `artist` is supported.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetTypeQueryParameterType
    {
        [EnumMember(Value = "artist")]
        #pragma warning disable CS1591
        Artist,
        #pragma warning restore CS1591
    }
}
