{
 "openapi": "3.0.3",
 "info": {
  "description": "You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.\n\nIn order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</[...]",
  "version": "1.0.0",
  "title": "Spotify Web API",
  "termsOfService": "https://developer.spotify.com/terms/",
  "contact": {
   "name": "Spotify for Developers Community",
   "url": "https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer"
  }
 },
 "servers": [
  {
   "url": "https://api.spotify.com/v1"
  }
 ],
 "tags": [
  {
   "name": "Albums"
  },
  {
   "name": "Artists"
  },
  {
   "name": "Audiobooks"
  },
  {
   "name": "Categories"
  },
  {
   "name": "Chapters"
  },
  {
   "name": "Episodes"
  },
  {
   "name": "Library"
  },
  {
   "name": "Genres"
  },
  {
   "name": "Markets"
  },
  {
   "name": "Player"
  },
  {
   "name": "Playlists"
  },
  {
   "name": "Search"
  },
  {
   "name": "Shows"
  },
  {
   "name": "Tracks"
  },
  {
   "name": "Users"
  }
 ],
 "paths": {
  "/albums/{id}": {
   "get": {
    "operationId": "get-an-album",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Albums"
    ],
    "summary": "Get Album\n",
    "description": "Get Spotify catalog information for a single album.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/albums": {
   "get": {
    "deprecated": true,
    "operationId": "get-multiple-albums",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Albums"
    ],
    "summary": "Get Several Albums\n",
    "description": "Get Spotify catalog information for multiple albums identified by their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/albums/{id}/tracks": {
   "get": {
    "operationId": "get-an-albums-tracks",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Albums",
     "Tracks"
    ],
    "summary": "Get Album Tracks\n",
    "description": "Get Spotify catalog information about an album’s tracks.\nOptional parameters can be used to limit the number of tracks returned.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/artists/{id}": {
   "get": {
    "tags": [
     "Artists"
    ],
    "operationId": "get-an-artist",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Artist\n",
    "description": "Get Spotify catalog information for a single artist identified by their unique Spotify ID.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/artists": {
   "get": {
    "deprecated": true,
    "tags": [
     "Artists"
    ],
    "operationId": "get-multiple-artists",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Several Artists\n",
    "description": "Get Spotify catalog information for several artists based on their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/artists/{id}/albums": {
   "get": {
    "tags": [
     "Artists",
     "Albums"
    ],
    "operationId": "get-an-artists-albums",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Artist's Albums\n",
    "description": "Get Spotify catalog information about an artist's albums.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/artists/{id}/top-tracks": {
   "get": {
    "deprecated": true,
    "tags": [
     "Artists",
     "Tracks"
    ],
    "operationId": "get-an-artists-top-tracks",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Artist's Top Tracks\n",
    "description": "Get Spotify catalog information about an artist's top tracks by country.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/artists/{id}/related-artists": {
   "get": {
    "deprecated": true,
    "tags": [
     "Artists"
    ],
    "operationId": "get-an-artists-related-artists",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Artist's Related Artists\n",
    "description": "Get Spotify catalog information about artists similar to a given artist. Similarity is based on analysis of the Spotify community's listening history.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/shows/{id}": {
   "get": {
    "tags": [
     "Shows"
    ],
    "operationId": "get-a-show",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Show\n",
    "description": "Get Spotify catalog information for a single show identified by its\nunique Spotify ID.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-read-playback-position"
      ]
     }
    ]
   }
  },
  "/shows": {
   "get": {
    "deprecated": true,
    "tags": [
     "Shows"
    ],
    "operationId": "get-multiple-shows",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Several Shows\n",
    "description": "Get Spotify catalog information for several shows based on their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/shows/{id}/episodes": {
   "get": {
    "tags": [
     "Shows",
     "Episodes"
    ],
    "operationId": "get-a-shows-episodes",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Show Episodes\n",
    "description": "Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-read-playback-position"
      ]
     }
    ]
   }
  },
  "/episodes/{id}": {
   "get": {
    "tags": [
     "Episodes"
    ],
    "operationId": "get-an-episode",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Episode\n",
    "description": "Get Spotify catalog information for a single episode identified by its\nunique Spotify ID.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-read-playback-position"
      ]
     }
    ]
   }
  },
  "/episodes": {
   "get": {
    "deprecated": true,
    "tags": [
     "Episodes"
    ],
    "operationId": "get-multiple-episodes",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "summary": "Get Several Episodes\n",
    "description": "Get Spotify catalog information for several episodes based on their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-read-playback-position"
      ]
     }
    ]
   }
  },
  "/audiobooks/{id}": {
   "get": {
    "operationId": "get-an-audiobook",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Audiobooks"
    ],
    "summary": "Get an Audiobook\n",
    "description": "Get Spotify catalog information for a single audiobook. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/audiobooks": {
   "get": {
    "deprecated": true,
    "operationId": "get-multiple-audiobooks",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Audiobooks"
    ],
    "summary": "Get Several Audiobooks\n",
    "description": "Get Spotify catalog information for several audiobooks identified by their Spotify IDs. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/audiobooks/{id}/chapters": {
   "get": {
    "operationId": "get-audiobook-chapters",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Audiobooks",
     "Chapters"
    ],
    "summary": "Get Audiobook Chapters\n",
    "description": "Get Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/me/audiobooks": {
   "get": {
    "tags": [
     "Audiobooks",
     "Library"
    ],
    "operationId": "get-users-saved-audiobooks",
    "summary": "Get User's Saved Audiobooks\n",
    "description": "Get a list of the audiobooks saved in the current Spotify user's 'Your Music' library.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Audiobooks",
     "Library"
    ],
    "operationId": "save-audiobooks-user",
    "summary": "Save Audiobooks for Current User\n",
    "description": "Save one or more audiobooks to the current Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Audiobooks",
     "Library"
    ],
    "operationId": "remove-audiobooks-user",
    "summary": "Remove User's Saved Audiobooks\n",
    "description": "Remove one or more audiobooks from the Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   }
  },
  "/me/audiobooks/contains": {
   "get": {
    "tags": [
     "Audiobooks",
     "Library"
    ],
    "operationId": "check-users-saved-audiobooks",
    "summary": "Check User's Saved Audiobooks\n",
    "deprecated": true,
    "description": "Check if one or more audiobooks are already saved in the current Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   }
  },
  "/chapters/{id}": {
   "get": {
    "operationId": "get-a-chapter",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Chapters"
    ],
    "summary": "Get a Chapter\n",
    "description": "Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/chapters": {
   "get": {
    "deprecated": true,
    "operationId": "get-several-chapters",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataPolicyList"
    },
    "tags": [
     "Chapters"
    ],
    "summary": "Get Several Chapters\n",
    "description": "Get Spotify catalog information for several audiobook chapters identified by their Spotify IDs. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/tracks/{id}": {
   "get": {
    "tags": [
     "Tracks"
    ],
    "operationId": "get-track",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Track\n",
    "description": "Get Spotify catalog information for a single track identified by its\nunique Spotify ID.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/tracks": {
   "get": {
    "deprecated": true,
    "tags": [
     "Tracks"
    ],
    "operationId": "get-several-tracks",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Several Tracks\n",
    "description": "Get Spotify catalog information for multiple tracks based on their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/search": {
   "get": {
    "tags": [
     "Search"
    ],
    "operationId": "search",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MachineLearning"
     }
    ],
    "summary": "Search for Item\n",
    "description": "Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/me": {
   "get": {
    "tags": [
     "Users"
    ],
    "operationId": "get-current-users-profile",
    "summary": "Get Current User's Profile\n",
    "description": "Get detailed profile information about the current user (including the\ncurrent user's username).\n",
    "security": [
     {
      "oauth_2_0": [
       "user-read-private",
       "user-read-email"
      ]
     }
    ]
   }
  },
  "/playlists/{playlist_id}": {
   "get": {
    "tags": [
     "Playlists"
    ],
    "operationId": "get-playlist",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Playlist\n",
    "description": "Get a playlist owned by a Spotify user.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   },
   "put": {
    "tags": [
     "Playlists",
     "Library"
    ],
    "operationId": "change-playlist-details",
    "summary": "Change Playlist Details\n",
    "description": "Change a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/playlists/{playlist_id}/tracks": {
   "get": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "get-playlists-tracks",
    "deprecated": true,
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Playlist Items [DEPRECATED]\n",
    "description": "**Deprecated:** Use [Get Playlist Items](/documentation/web-api/reference/get-playlists-items) instead.\n\nGet full details of the items of a playlist owned by a Spotify user.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-read-private"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "add-tracks-to-playlist",
    "deprecated": true,
    "summary": "Add Items to Playlist [DEPRECATED]\n",
    "description": "**Deprecated:** Use [Add Items to Playlist](/documentation/web-api/reference/add-items-to-playlist) instead.\n\nAdd one or more items to a user's playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "reorder-or-replace-playlists-tracks",
    "deprecated": true,
    "summary": "Update Playlist Items [DEPRECATED]\n",
    "description": "**Deprecated:** Use [Update Playlist Items](/documentation/web-api/reference/reorder-or-replace-playlists-items) instead.\n\nEither reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. T[...]",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "remove-tracks-playlist",
    "deprecated": true,
    "summary": "Remove Playlist Items [DEPRECATED]\n",
    "description": "**Deprecated:** Use [Remove Playlist Items](/documentation/web-api/reference/remove-items-playlist) instead.\n\nRemove one or more items from a user's playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/playlists/{playlist_id}/items": {
   "get": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "get-playlists-items",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Playlist Items\n",
    "description": "Get full details of the items of a playlist owned by a Spotify user.\n\n**Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-read-private"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "add-items-to-playlist",
    "summary": "Add Items to Playlist\n",
    "description": "Add one or more items to a user's playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   },
   "put": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "reorder-or-replace-playlists-items",
    "summary": "Update Playlist Items\n",
    "description": "Either reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.\n<br/>\n**Note**: Replace and reorder are mutually e[...]",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Playlists",
     "Tracks"
    ],
    "operationId": "remove-items-playlist",
    "summary": "Remove Playlist Items\n",
    "description": "Remove one or more items from a user's playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/me/playlists": {
   "get": {
    "tags": [
     "Playlists",
     "Library"
    ],
    "operationId": "get-a-list-of-current-users-playlists",
    "summary": "Get Current User's Playlists\n",
    "description": "Get a list of the playlists owned or followed by the current Spotify\nuser.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-read-private"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Playlists",
     "Library"
    ],
    "operationId": "create-playlist",
    "summary": "Create Playlist\n",
    "description": "Create a playlist for the current Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/me/library": {
   "put": {
    "tags": [
     "Library"
    ],
    "operationId": "save-library-items",
    "summary": "Save Items to Library\n",
    "description": "Add one or more items to the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify",
       "user-follow-modify",
       "playlist-modify-public"
      ]
     }
    ]
   },
   "delete": {
    "tags": [
     "Library"
    ],
    "operationId": "remove-library-items",
    "summary": "Remove Items from Library\n",
    "description": "Remove one or more items from the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify",
       "user-follow-modify",
       "playlist-modify-public"
      ]
     }
    ]
   }
  },
  "/me/library/contains": {
   "get": {
    "tags": [
     "Library"
    ],
    "operationId": "check-library-contains",
    "summary": "Check User's Saved Items\n",
    "description": "Check if one or more items are already saved in the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and playlists.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read",
       "user-follow-read",
       "playlist-read-private"
      ]
     }
    ]
   }
  },
  "/me/albums": {
   "get": {
    "tags": [
     "Albums",
     "Library"
    ],
    "operationId": "get-users-saved-albums",
    "summary": "Get User's Saved Albums\n",
    "description": "Get a list of the albums saved in the current Spotify user's 'Your Music' library.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Albums",
     "Library"
    ],
    "operationId": "save-albums-user",
    "summary": "Save Albums for Current User\n",
    "description": "Save one or more albums to the current user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Albums",
     "Library"
    ],
    "operationId": "remove-albums-user",
    "summary": "Remove Users' Saved Albums\n",
    "description": "Remove one or more albums from the current user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   }
  },
  "/me/albums/contains": {
   "get": {
    "tags": [
     "Albums",
     "Library"
    ],
    "operationId": "check-users-saved-albums",
    "summary": "Check User's Saved Albums\n",
    "deprecated": true,
    "description": "Check if one or more albums is already saved in the current Spotify user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   }
  },
  "/me/tracks": {
   "get": {
    "tags": [
     "Tracks",
     "Library"
    ],
    "operationId": "get-users-saved-tracks",
    "summary": "Get User's Saved Tracks\n",
    "description": "Get a list of the songs saved in the current Spotify user's 'Your Music' library.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Tracks",
     "Library"
    ],
    "operationId": "save-tracks-user",
    "summary": "Save Tracks for Current User\n",
    "description": "Save one or more tracks to the current user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Tracks",
     "Library"
    ],
    "operationId": "remove-tracks-user",
    "summary": "Remove User's Saved Tracks\n",
    "description": "Remove one or more tracks from the current user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   }
  },
  "/me/tracks/contains": {
   "get": {
    "tags": [
     "Tracks",
     "Library"
    ],
    "operationId": "check-users-saved-tracks",
    "summary": "Check User's Saved Tracks\n",
    "deprecated": true,
    "description": "Check if one or more tracks is already saved in the current Spotify user's 'Your Music' library.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   }
  },
  "/me/episodes": {
   "get": {
    "tags": [
     "Episodes",
     "Library"
    ],
    "operationId": "get-users-saved-episodes",
    "summary": "Get User's Saved Episodes\n",
    "description": "Get a list of the episodes saved in the current Spotify user's library.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read",
       "user-read-playback-position"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Episodes",
     "Library"
    ],
    "operationId": "save-episodes-user",
    "summary": "Save Episodes for Current User\n",
    "description": "Save one or more episodes to the current user's library.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Episodes",
     "Library"
    ],
    "operationId": "remove-episodes-user",
    "summary": "Remove User's Saved Episodes\n",
    "description": "Remove one or more episodes from the current user's library.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   }
  },
  "/me/episodes/contains": {
   "get": {
    "tags": [
     "Episodes",
     "Library"
    ],
    "operationId": "check-users-saved-episodes",
    "summary": "Check User's Saved Episodes\n",
    "deprecated": true,
    "description": "Check if one or more episodes is already saved in the current Spotify user's 'Your Episodes' library.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   }
  },
  "/me/shows": {
   "get": {
    "tags": [
     "Shows",
     "Library"
    ],
    "operationId": "get-users-saved-shows",
    "summary": "Get User's Saved Shows\n",
    "description": "Get a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Shows",
     "Library"
    ],
    "operationId": "save-shows-user",
    "summary": "Save Shows for Current User\n",
    "description": "Save one or more shows to current Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Shows",
     "Library"
    ],
    "operationId": "remove-shows-user",
    "summary": "Remove User's Saved Shows\n",
    "description": "Delete one or more shows from current Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-modify"
      ]
     }
    ]
   }
  },
  "/me/shows/contains": {
   "get": {
    "tags": [
     "Shows",
     "Library"
    ],
    "operationId": "check-users-saved-shows",
    "summary": "Check User's Saved Shows\n",
    "deprecated": true,
    "description": "Check if one or more shows is already saved in the current Spotify user's library.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-library-read"
      ]
     }
    ]
   }
  },
  "/me/top/{type}": {
   "get": {
    "tags": [
     "Users",
     "Tracks",
     "Library"
    ],
    "operationId": "get-users-top-artists-and-tracks",
    "summary": "Get User's Top Items\n",
    "description": "Get the current user's top artists or tracks based on calculated affinity.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-top-read"
      ]
     }
    ]
   }
  },
  "/users/{user_id}": {
   "get": {
    "deprecated": true,
    "tags": [
     "Users"
    ],
    "operationId": "get-users-profile",
    "summary": "Get User's Profile\n",
    "description": "Get public profile information about a Spotify user.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/users/{user_id}/playlists": {
   "get": {
    "deprecated": true,
    "tags": [
     "Playlists",
     "Users"
    ],
    "operationId": "get-list-users-playlists",
    "summary": "Get User's Playlists\n",
    "description": "Get a list of the playlists owned or followed by a Spotify user.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-read-private",
       "playlist-read-collaborative"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Playlists",
     "Library"
    ],
    "operationId": "create-playlist-for-user",
    "deprecated": true,
    "summary": "Create Playlist for user\n",
    "description": "**Deprecated**: Use [Create Playlist](/documentation/web-api/reference/create-playlist) instead.\n\nCreate a playlist for a Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/playlists/{playlist_id}/followers": {
   "put": {
    "deprecated": true,
    "tags": [
     "Users",
     "Playlists"
    ],
    "operationId": "follow-playlist",
    "description": "Add the current user as a follower of a playlist.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "summary": "Follow Playlist\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Users",
     "Playlists"
    ],
    "operationId": "unfollow-playlist",
    "summary": "Unfollow Playlist\n",
    "description": "Remove the current user as a follower of a playlist.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/browse/featured-playlists": {
   "get": {
    "deprecated": true,
    "tags": [
     "Playlists"
    ],
    "operationId": "get-featured-playlists",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MultipleIntegrations"
     }
    ],
    "summary": "Get Featured Playlists\n",
    "description": "Get a list of Spotify featured playlists (shown, for example, on a Spotify player's 'Browse' tab).\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/browse/categories": {
   "get": {
    "deprecated": true,
    "tags": [
     "Categories"
    ],
    "operationId": "get-categories",
    "summary": "Get Several Browse Categories\n",
    "description": "Get a list of categories used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/browse/categories/{category_id}": {
   "get": {
    "deprecated": true,
    "tags": [
     "Categories"
    ],
    "operationId": "get-a-category",
    "summary": "Get Single Browse Category\n",
    "description": "Get a single category used to tag items in Spotify (on, for example, the Spotify player’s “Browse” tab).\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/browse/categories/{category_id}/playlists": {
   "get": {
    "deprecated": true,
    "tags": [
     "Playlists",
     "Categories"
    ],
    "operationId": "get-a-categories-playlists",
    "summary": "Get Category's Playlists\n",
    "description": "Get a list of Spotify playlists tagged with a particular category.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/playlists/{playlist_id}/images": {
   "get": {
    "tags": [
     "Playlists"
    ],
    "operationId": "get-playlist-cover",
    "x-spotify-policy-list": {
     "$ref": "#/components/x-spotify-policy/metadataWithMachineLearningPolicyList"
    },
    "summary": "Get Playlist Cover Image\n",
    "description": "Get the current image associated with a specific playlist.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   },
   "put": {
    "tags": [
     "Playlists"
    ],
    "operationId": "upload-custom-playlist-cover",
    "summary": "Add Custom Playlist Cover Image\n",
    "description": "Replace the image used to represent a specific playlist.\n",
    "security": [
     {
      "oauth_2_0": [
       "ugc-image-upload",
       "playlist-modify-public",
       "playlist-modify-private"
      ]
     }
    ]
   }
  },
  "/browse/new-releases": {
   "get": {
    "deprecated": true,
    "tags": [
     "Albums"
    ],
    "operationId": "get-new-releases",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MultipleIntegrations"
     }
    ],
    "summary": "Get New Releases\n",
    "description": "Get a list of new album releases featured in Spotify (shown, for example, on a Spotify player’s “Browse” tab).\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/me/following": {
   "get": {
    "tags": [
     "Users",
     "Library",
     "Artists"
    ],
    "operationId": "get-followed",
    "summary": "Get Followed Artists\n",
    "description": "Get the current user's followed artists.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-follow-read"
      ]
     }
    ]
   },
   "put": {
    "deprecated": true,
    "tags": [
     "Users",
     "Artists",
     "Library"
    ],
    "operationId": "follow-artists-users",
    "summary": "Follow Artists or Users\n",
    "description": "Add the current user as a follower of one or more artists or other Spotify users.\n\n**Note:** This endpoint is deprecated. Use [Save Items to Library](/documentation/web-api/reference/save-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-follow-modify"
      ]
     }
    ]
   },
   "delete": {
    "deprecated": true,
    "tags": [
     "Users",
     "Artists",
     "Library"
    ],
    "operationId": "unfollow-artists-users",
    "summary": "Unfollow Artists or Users\n",
    "description": "Remove the current user as a follower of one or more artists or other Spotify users.\n\n**Note:** This endpoint is deprecated. Use [Remove Items from Library](/documentation/web-api/reference/remove-library-items) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-follow-modify"
      ]
     }
    ]
   }
  },
  "/me/following/contains": {
   "get": {
    "tags": [
     "Users",
     "Artists",
     "Library"
    ],
    "operationId": "check-current-user-follows",
    "summary": "Check If User Follows Artists or Users\n",
    "deprecated": true,
    "description": "Check to see if the current user is following one or more artists or other Spotify users.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": [
       "user-follow-read"
      ]
     }
    ]
   }
  },
  "/playlists/{playlist_id}/followers/contains": {
   "get": {
    "tags": [
     "Users",
     "Playlists"
    ],
    "operationId": "check-if-user-follows-playlist",
    "summary": "Check if Current User Follows Playlist\n",
    "deprecated": true,
    "description": "Check to see if the current user is following a specified playlist.\n\n**Note:** This endpoint is deprecated. Use [Check User's Saved Items](/documentation/web-api/reference/check-library-contains) instead.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/audio-features": {
   "get": {
    "deprecated": true,
    "tags": [
     "Tracks"
    ],
    "operationId": "get-several-audio-features",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MachineLearning"
     }
    ],
    "summary": "Get Several Tracks' Audio Features\n",
    "description": "Get audio features for multiple tracks based on their Spotify IDs.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/audio-features/{id}": {
   "get": {
    "deprecated": true,
    "tags": [
     "Tracks"
    ],
    "operationId": "get-audio-features",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MachineLearning"
     }
    ],
    "summary": "Get Track's Audio Features\n",
    "description": "Get audio feature information for a single track identified by its unique\nSpotify ID.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/audio-analysis/{id}": {
   "get": {
    "deprecated": true,
    "tags": [
     "Tracks"
    ],
    "operationId": "get-audio-analysis",
    "summary": "Get Track's Audio Analysis\n",
    "description": "Get a low-level audio analysis for a track in the Spotify catalog. The audio analysis describes the track’s structure and musical content, including rhythm, pitch, and timbre.\n",
    "security": [
     {
      "oauth_2_0": []
     }
    ]
   }
  },
  "/recommendations": {
   "get": {
    "deprecated": true,
    "tags": [
     "Tracks"
    ],
    "operationId": "get-recommendations",
    "x-spotify-policy-list": [
     {
      "$ref": "#/components/x-spotify-policy/policies/MachineLearning"
     }
    ],
    "summary": "Get Recommendations\n",
    "description": "Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.\n\nFor artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.\n"
   }
  }
 }
}