// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Me.Albums;
using Soenneker.Spotify.OpenApiClient.Me.Audiobooks;
using Soenneker.Spotify.OpenApiClient.Me.Episodes;
using Soenneker.Spotify.OpenApiClient.Me.Following;
using Soenneker.Spotify.OpenApiClient.Me.Library;
using Soenneker.Spotify.OpenApiClient.Me.Player;
using Soenneker.Spotify.OpenApiClient.Me.Playlists;
using Soenneker.Spotify.OpenApiClient.Me.Shows;
using Soenneker.Spotify.OpenApiClient.Me.Top;
using Soenneker.Spotify.OpenApiClient.Me.Tracks;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Me
{
    /// <summary>
    /// Builds and executes requests for operations under \me
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The albums property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Albums.AlbumsRequestBuilder Albums
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Albums.AlbumsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The audiobooks property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Audiobooks.AudiobooksRequestBuilder Audiobooks
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Audiobooks.AudiobooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The episodes property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Episodes.EpisodesRequestBuilder Episodes
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Episodes.EpisodesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The following property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Following.FollowingRequestBuilder Following
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Following.FollowingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The library property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Library.LibraryRequestBuilder Library
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Library.LibraryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The player property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder Player
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The playlists property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Playlists.PlaylistsRequestBuilder Playlists
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Playlists.PlaylistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shows property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Shows.ShowsRequestBuilder Shows
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Shows.ShowsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The top property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Top.TopRequestBuilder Top
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Top.TopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tracks property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Tracks.TracksRequestBuilder Tracks
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Tracks.TracksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", rawUrl)
        {
        }
        /// <summary>
        /// Get detailed profile information about the current user (including thecurrent user&apos;s username).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Models.PrivateUserObject.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get detailed profile information about the current user (including thecurrent user&apos;s username).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Me.MeRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Spotify.OpenApiClient.Me.MeRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Me.MeRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
