// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Albums.Item;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Albums
{
    /// <summary>
    /// Builds and executes requests for operations under \albums
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AlbumsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Spotify.OpenApiClient.albums.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.Item.AlbumsItemRequestBuilder"/></returns>
        public global::Soenneker.Spotify.OpenApiClient.Albums.Item.AlbumsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Spotify.OpenApiClient.Albums.Item.AlbumsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlbumsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/albums?ids={ids}{&market*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AlbumsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/albums?ids={ids}{&market*}", rawUrl)
        {
        }
        /// <summary>
        /// Get Spotify catalog information for multiple albums identified by their Spotify IDs.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums429Error">When receiving a 429 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsGetResponse?> GetAsAlbumsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsGetResponse> GetAsAlbumsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.Albums401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.Albums403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.Albums429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsGetResponse>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Spotify catalog information for multiple albums identified by their Spotify IDs.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Albums429Error">When receiving a 429 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsAlbumsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.Albums401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.Albums403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.Albums429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsResponse>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Spotify catalog information for multiple albums identified by their Spotify IDs.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get Spotify catalog information for multiple albums identified by their Spotify IDs.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AlbumsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("market")]
            public string? Market { get; set; }
#nullable restore
#else
            [QueryParameter("market")]
            public string Market { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AlbumsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Albums.AlbumsRequestBuilder.AlbumsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
