// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Models;
using Soenneker.Spotify.OpenApiClient.Recommendations.AvailableGenreSeeds;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Recommendations
{
    /// <summary>
    /// Builds and executes requests for operations under \recommendations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecommendationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The availableGenreSeeds property</summary>
        [Obsolete("")]
        public global::Soenneker.Spotify.OpenApiClient.Recommendations.AvailableGenreSeeds.AvailableGenreSeedsRequestBuilder AvailableGenreSeeds
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Recommendations.AvailableGenreSeeds.AvailableGenreSeedsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecommendationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/recommendations?seed_artists={seed_artists}&seed_genres={seed_genres}&seed_tracks={seed_tracks}{&limit*,market*,max_acousticness*,max_danceability*,max_duration_ms*,max_energy*,max_instrumentalness*,max_key*,max_liveness*,max_loudness*,max_mode*,max_popularity*,max_speechiness*,max_tempo*,max_time_signature*,max_valence*,min_acousticness*,min_danceability*,min_duration_ms*,min_energy*,min_instrumentalness*,min_key*,min_liveness*,min_loudness*,min_mode*,min_popularity*,min_speechiness*,min_tempo*,min_time_signature*,min_valence*,target_acousticness*,target_danceability*,target_duration_ms*,target_energy*,target_instrumentalness*,target_key*,target_liveness*,target_loudness*,target_mode*,target_popularity*,target_speechiness*,target_tempo*,target_time_signature*,target_valence*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecommendationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/recommendations?seed_artists={seed_artists}&seed_genres={seed_genres}&seed_tracks={seed_tracks}{&limit*,market*,max_acousticness*,max_danceability*,max_duration_ms*,max_energy*,max_instrumentalness*,max_key*,max_liveness*,max_loudness*,max_mode*,max_popularity*,max_speechiness*,max_tempo*,max_time_signature*,max_valence*,min_acousticness*,min_danceability*,min_duration_ms*,min_energy*,min_instrumentalness*,min_key*,min_liveness*,min_loudness*,min_mode*,min_popularity*,min_speechiness*,min_tempo*,min_time_signature*,min_valence*,target_acousticness*,target_danceability*,target_duration_ms*,target_energy*,target_instrumentalness*,target_key*,target_liveness*,target_loudness*,target_mode*,target_popularity*,target_speechiness*,target_tempo*,target_time_signature*,target_valence*}", rawUrl)
        {
        }
        /// <summary>
        /// Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Models.RecommendationsObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.UnauthorizedResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.ForbiddenResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.TooManyRequestsResponse">When receiving a 429 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.RecommendationsObject?> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.RecommendationsObject> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.UnauthorizedResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.ForbiddenResponse.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.TooManyRequestsResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Models.RecommendationsObject>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Models.RecommendationsObject.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder.RecommendationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Recommendations.RecommendationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Recommendations are generated based on the available information for a given seed entity and matched against similar artists and tracks. If there is sufficient information about the provided seeds, a list of tracks will be returned together with pool size details.For artists and tracks that are very new or obscure there might not be enough data to generate a list of tracks.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecommendationsRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("market")]
            public string? Market { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("market")]
            public string Market { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("max_acousticness")]
            public double? MaxAcousticness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_danceability")]
            public double? MaxDanceability { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_duration_ms")]
            public int? MaxDurationMs { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_energy")]
            public double? MaxEnergy { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_instrumentalness")]
            public double? MaxInstrumentalness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_key")]
            public int? MaxKey { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_liveness")]
            public double? MaxLiveness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_loudness")]
            public double? MaxLoudness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_mode")]
            public int? MaxMode { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_popularity")]
            public int? MaxPopularity { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_speechiness")]
            public double? MaxSpeechiness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_tempo")]
            public double? MaxTempo { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_time_signature")]
            public int? MaxTimeSignature { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("max_valence")]
            public double? MaxValence { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_acousticness")]
            public double? MinAcousticness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_danceability")]
            public double? MinDanceability { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_duration_ms")]
            public int? MinDurationMs { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_energy")]
            public double? MinEnergy { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_instrumentalness")]
            public double? MinInstrumentalness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_key")]
            public int? MinKey { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_liveness")]
            public double? MinLiveness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_loudness")]
            public double? MinLoudness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_mode")]
            public int? MinMode { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_popularity")]
            public int? MinPopularity { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_speechiness")]
            public double? MinSpeechiness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_tempo")]
            public double? MinTempo { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_time_signature")]
            public int? MinTimeSignature { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("min_valence")]
            public double? MinValence { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("seed_artists")]
            public string? SeedArtists { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("seed_artists")]
            public string SeedArtists { get; set; }
            #pragma warning restore CS1591
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("seed_genres")]
            public string? SeedGenres { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("seed_genres")]
            public string SeedGenres { get; set; }
            #pragma warning restore CS1591
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("seed_tracks")]
            public string? SeedTracks { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("seed_tracks")]
            public string SeedTracks { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("target_acousticness")]
            public double? TargetAcousticness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_danceability")]
            public double? TargetDanceability { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_duration_ms")]
            public int? TargetDurationMs { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_energy")]
            public double? TargetEnergy { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_instrumentalness")]
            public double? TargetInstrumentalness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_key")]
            public int? TargetKey { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_liveness")]
            public double? TargetLiveness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_loudness")]
            public double? TargetLoudness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_mode")]
            public int? TargetMode { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_popularity")]
            public int? TargetPopularity { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_speechiness")]
            public double? TargetSpeechiness { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_tempo")]
            public double? TargetTempo { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_time_signature")]
            public int? TargetTimeSignature { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("target_valence")]
            public double? TargetValence { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
