// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Me.Player.CurrentlyPlaying;
using Soenneker.Spotify.OpenApiClient.Me.Player.Devices;
using Soenneker.Spotify.OpenApiClient.Me.Player.Next;
using Soenneker.Spotify.OpenApiClient.Me.Player.Pause;
using Soenneker.Spotify.OpenApiClient.Me.Player.Play;
using Soenneker.Spotify.OpenApiClient.Me.Player.Previous;
using Soenneker.Spotify.OpenApiClient.Me.Player.Queue;
using Soenneker.Spotify.OpenApiClient.Me.Player.RecentlyPlayed;
using Soenneker.Spotify.OpenApiClient.Me.Player.Repeat;
using Soenneker.Spotify.OpenApiClient.Me.Player.Seek;
using Soenneker.Spotify.OpenApiClient.Me.Player.Shuffle;
using Soenneker.Spotify.OpenApiClient.Me.Player.Volume;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Me.Player
{
    /// <summary>
    /// Builds and executes requests for operations under \me\player
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PlayerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The currentlyPlaying property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.CurrentlyPlaying.CurrentlyPlayingRequestBuilder CurrentlyPlaying
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.CurrentlyPlaying.CurrentlyPlayingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The next property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Next.NextRequestBuilder Next
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Next.NextRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pause property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Pause.PauseRequestBuilder Pause
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Pause.PauseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The play property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Play.PlayRequestBuilder Play
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Play.PlayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The previous property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Previous.PreviousRequestBuilder Previous
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Previous.PreviousRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The queue property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Queue.QueueRequestBuilder Queue
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Queue.QueueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recentlyPlayed property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.RecentlyPlayed.RecentlyPlayedRequestBuilder RecentlyPlayed
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.RecentlyPlayed.RecentlyPlayedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The repeat property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Repeat.RepeatRequestBuilder Repeat
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Repeat.RepeatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seek property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Seek.SeekRequestBuilder Seek
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Seek.SeekRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shuffle property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Shuffle.ShuffleRequestBuilder Shuffle
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Shuffle.ShuffleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The volume property</summary>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.Volume.VolumeRequestBuilder Volume
        {
            get => new global::Soenneker.Spotify.OpenApiClient.Me.Player.Volume.VolumeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/player{?additional_types*,market*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PlayerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/player{?additional_types*,market*}", rawUrl)
        {
        }
        /// <summary>
        /// Get information about the user’s current playback state, including track or episode, progress, and active device.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject?> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder.PlayerRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder.PlayerRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Models.CurrentlyPlayingContextObject.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Player401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Player403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Player429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PutAsync(global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PutAsync(global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.Player401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.Player403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.Player429Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get information about the user’s current playback state, including track or episode, progress, and active device.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder.PlayerRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder.PlayerRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerPutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Me.Player.PlayerRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get information about the user’s current playback state, including track or episode, progress, and active device.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PlayerRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("additional_types")]
            public string? AdditionalTypes { get; set; }
#nullable restore
#else
            [QueryParameter("additional_types")]
            public string AdditionalTypes { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("market")]
            public string? Market { get; set; }
#nullable restore
#else
            [QueryParameter("market")]
            public string Market { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
