// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists
{
    /// <summary>
    /// Builds and executes requests for operations under \browse\featured-playlists
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FeaturedPlaylistsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeaturedPlaylistsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/browse/featured-playlists{?limit*,locale*,offset*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FeaturedPlaylistsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/browse/featured-playlists{?limit*,locale*,offset*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of Spotify featured playlists (shown, for example, on a Spotify player&apos;s &apos;Browse&apos; tab).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject429Error">When receiving a 429 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject?> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder.FeaturedPlaylistsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder.FeaturedPlaylistsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject>(requestInfo, global::Soenneker.Spotify.OpenApiClient.Models.PagingFeaturedPlaylistObject.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of Spotify featured playlists (shown, for example, on a Spotify player&apos;s &apos;Browse&apos; tab).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder.FeaturedPlaylistsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder.FeaturedPlaylistsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Browse.FeaturedPlaylists.FeaturedPlaylistsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of Spotify featured playlists (shown, for example, on a Spotify player&apos;s &apos;Browse&apos; tab).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class FeaturedPlaylistsRequestBuilderGetQueryParameters 
        {
            [QueryParameter("limit")]
            public int? Limit { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("locale")]
            public string? Locale { get; set; }
#nullable restore
#else
            [QueryParameter("locale")]
            public string Locale { get; set; }
#endif
            [QueryParameter("offset")]
            public int? Offset { get; set; }
        }
    }
}
#pragma warning restore CS0618
