// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Spotify.OpenApiClient.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The albums property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAlbumObject? Albums { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAlbumObject Albums { get; set; }
#endif
        /// <summary>The artists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingArtistObject? Artists { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingArtistObject Artists { get; set; }
#endif
        /// <summary>The audiobooks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAudiobookObject? Audiobooks { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAudiobookObject Audiobooks { get; set; }
#endif
        /// <summary>The episodes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedEpisodeObject? Episodes { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedEpisodeObject Episodes { get; set; }
#endif
        /// <summary>The playlists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingPlaylistObject? Playlists { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingPlaylistObject Playlists { get; set; }
#endif
        /// <summary>The shows property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedShowObject? Shows { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedShowObject Shows { get; set; }
#endif
        /// <summary>The tracks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingTrackObject? Tracks { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PagingTrackObject Tracks { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Search.SearchGetResponse"/> and sets the default values.
        /// </summary>
        public SearchGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Search.SearchGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Spotify.OpenApiClient.Search.SearchGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Spotify.OpenApiClient.Search.SearchGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "albums", n => { Albums = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAlbumObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAlbumObject.CreateFromDiscriminatorValue); } },
                { "artists", n => { Artists = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingArtistObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingArtistObject.CreateFromDiscriminatorValue); } },
                { "audiobooks", n => { Audiobooks = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAudiobookObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAudiobookObject.CreateFromDiscriminatorValue); } },
                { "episodes", n => { Episodes = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedEpisodeObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedEpisodeObject.CreateFromDiscriminatorValue); } },
                { "playlists", n => { Playlists = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingPlaylistObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingPlaylistObject.CreateFromDiscriminatorValue); } },
                { "shows", n => { Shows = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedShowObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedShowObject.CreateFromDiscriminatorValue); } },
                { "tracks", n => { Tracks = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingTrackObject>(global::Soenneker.Spotify.OpenApiClient.Models.PagingTrackObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAlbumObject>("albums", Albums);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingArtistObject>("artists", Artists);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedAudiobookObject>("audiobooks", Audiobooks);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedEpisodeObject>("episodes", Episodes);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingPlaylistObject>("playlists", Playlists);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingSimplifiedShowObject>("shows", Shows);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PagingTrackObject>("tracks", Tracks);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
