// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains
{
    /// <summary>
    /// Builds and executes requests for operations under \playlists\{playlist_id}\followers\contains
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContainsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlist_id}/followers/contains{?ids*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContainsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/playlists/{playlist_id}/followers/contains{?ids*}", rawUrl)
        {
        }
        /// <summary>
        /// Check to see if the current user is following a specified playlist.**Note:** This endpoint is deprecated. Use [Check User&apos;s Saved Items](/documentation/web-api/reference/check-library-contains) instead.
        /// </summary>
        /// <returns>A List&lt;bool&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Contains401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Contains403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Spotify.OpenApiClient.Models.Contains429Error">When receiving a 429 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<bool?>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder.ContainsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<bool?>> GetAsync(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder.ContainsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Spotify.OpenApiClient.Models.Contains401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Spotify.OpenApiClient.Models.Contains403Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Spotify.OpenApiClient.Models.Contains429Error.CreateFromDiscriminatorValue },
            };
            var collectionResult = await RequestAdapter.SendPrimitiveCollectionAsync<bool?>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Check to see if the current user is following a specified playlist.**Note:** This endpoint is deprecated. Use [Check User&apos;s Saved Items](/documentation/web-api/reference/check-library-contains) instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder.ContainsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder.ContainsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Check to see if the current user is following a specified playlist.**Note:** This endpoint is deprecated. Use [Check User&apos;s Saved Items](/documentation/web-api/reference/check-library-contains) instead.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContainsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ContainsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Spotify.OpenApiClient.Playlists.Item.Followers.Contains.ContainsRequestBuilder.ContainsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
