// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Me.Following.Contains
{
    /// <summary>The ID type: either `artist` or `user`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetTypeQueryParameterType
    {
        [EnumMember(Value = "artist")]
        #pragma warning disable CS1591
        Artist,
        #pragma warning restore CS1591
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
    }
}
