// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Soenneker.Spotify.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Spotify.OpenApiClient.Me.Top.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTypeGetResponse : global::Soenneker.Spotify.OpenApiClient.Models.PagingObject, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items>? Items { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items> Items { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items>(global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items>("items", Items);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject"/>, <see cref="global::Soenneker.Spotify.OpenApiClient.Models.TrackObject"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTypeGetResponse_items : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject? ArtistObject { get; set; }
#nullable restore
#else
            public global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject ArtistObject { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Spotify.OpenApiClient.Models.TrackObject"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Spotify.OpenApiClient.Models.TrackObject? TrackObject { get; set; }
#nullable restore
#else
            public global::Soenneker.Spotify.OpenApiClient.Models.TrackObject TrackObject { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.Spotify.OpenApiClient.Me.Top.Item.WithTypeGetResponse.WithTypeGetResponse_items();
                if("ArtistObject".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ArtistObject = new global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject();
                }
                else if("TrackObject".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.TrackObject = new global::Soenneker.Spotify.OpenApiClient.Models.TrackObject();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ArtistObject != null)
                {
                    return ArtistObject.GetFieldDeserializers();
                }
                else if(TrackObject != null)
                {
                    return TrackObject.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ArtistObject != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.ArtistObject>(null, ArtistObject);
                }
                else if(TrackObject != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.TrackObject>(null, TrackObject);
                }
            }
        }
    }
}
#pragma warning restore CS0618
