// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    /// <summary>The object type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AlbumBase_type
    {
        [EnumMember(Value = "album")]
        #pragma warning disable CS1591
        Album,
        #pragma warning restore CS1591
    }
}
