// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    /// <summary>The type of the album.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AlbumBase_album_type
    {
        [EnumMember(Value = "album")]
        #pragma warning disable CS1591
        Album,
        #pragma warning restore CS1591
        [EnumMember(Value = "single")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
        [EnumMember(Value = "compilation")]
        #pragma warning disable CS1591
        Compilation,
        #pragma warning restore CS1591
    }
}
