// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    /// <summary>If `include_external=audio` is specified it signals that the client can play externally hosted audio content, and marksthe content as playable in the response. By default externally hosted audio content is marked as unplayable in the response.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SearchIncludeExternalParameter
    {
        [EnumMember(Value = "audio")]
        #pragma warning disable CS1591
        Audio,
        #pragma warning restore CS1591
    }
}
