// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SimplifiedPlaylistObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>`true` if the owner allows other users to modify the playlist.</summary>
        public bool? Collaborative { get; set; }
        /// <summary>The playlist description. _Only returned for modified, verified playlists, otherwise_ `null`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Known external URLs for this playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.ExternalUrlObject? ExternalUrls { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.ExternalUrlObject ExternalUrls { get; set; }
#endif
        /// <summary>A link to the Web API endpoint providing full details of the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Href { get; set; }
#nullable restore
#else
        public string Href { get; set; }
#endif
        /// <summary>The [Spotify ID](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Images for the playlist. The array may be empty or contain up to three images. The images are returned by size in descending order. See [Working with Playlists](/documentation/web-api/concepts/playlists). _**Note**: If returned, the source URL for the image (`url`) is temporary and will expire in less than a day._</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Spotify.OpenApiClient.Models.ImageObject>? Images { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Spotify.OpenApiClient.Models.ImageObject> Images { get; set; }
#endif
        /// <summary>A collection containing a link ( `href` ) to the Web API endpoint where full details of the playlist&apos;s items can be retrieved, along with the `total` number of items in the playlist. Note, a track object may be `null`. This can happen if a track is no longer available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject? Items { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject Items { get; set; }
#endif
        /// <summary>The name of the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The user who owns the playlist</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistOwnerObject? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistOwnerObject Owner { get; set; }
#endif
        /// <summary>The playlist&apos;s public/private status (if it is added to the user&apos;s profile): `true` the playlist is public, `false` the playlist is private, `null` the playlist status is not relevant. For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)</summary>
        public bool? Public { get; set; }
        /// <summary>The version identifier for the current playlist. Can be supplied in other requests to target a specific playlist version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SnapshotId { get; set; }
#nullable restore
#else
        public string SnapshotId { get; set; }
#endif
        /// <summary>**Deprecated:** Use `items` instead. A collection containing a link ( `href` ) to the Web API endpoint where full details of the playlist&apos;s tracks can be retrieved, along with the `total` number of tracks in the playlist. Note, a track object may be `null`. This can happen if a track is no longer available.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject? Tracks { get; set; }
#nullable restore
#else
        public global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject Tracks { get; set; }
#endif
        /// <summary>The object type: &quot;playlist&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the playlist.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Spotify.OpenApiClient.Models.SimplifiedPlaylistObject"/> and sets the default values.
        /// </summary>
        public SimplifiedPlaylistObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Spotify.OpenApiClient.Models.SimplifiedPlaylistObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Spotify.OpenApiClient.Models.SimplifiedPlaylistObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Spotify.OpenApiClient.Models.SimplifiedPlaylistObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collaborative", n => { Collaborative = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "external_urls", n => { ExternalUrls = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.ExternalUrlObject>(global::Soenneker.Spotify.OpenApiClient.Models.ExternalUrlObject.CreateFromDiscriminatorValue); } },
                { "href", n => { Href = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::Soenneker.Spotify.OpenApiClient.Models.ImageObject>(global::Soenneker.Spotify.OpenApiClient.Models.ImageObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "items", n => { Items = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject>(global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistOwnerObject>(global::Soenneker.Spotify.OpenApiClient.Models.PlaylistOwnerObject.CreateFromDiscriminatorValue); } },
                { "public", n => { Public = n.GetBoolValue(); } },
                { "snapshot_id", n => { SnapshotId = n.GetStringValue(); } },
                { "tracks", n => { Tracks = n.GetObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject>(global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("collaborative", Collaborative);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.ExternalUrlObject>("external_urls", ExternalUrls);
            writer.WriteStringValue("href", Href);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Spotify.OpenApiClient.Models.ImageObject>("images", Images);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject>("items", Items);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistOwnerObject>("owner", Owner);
            writer.WriteBoolValue("public", Public);
            writer.WriteStringValue("snapshot_id", SnapshotId);
            writer.WriteObjectValue<global::Soenneker.Spotify.OpenApiClient.Models.PlaylistTracksRefObject>("tracks", Tracks);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
