// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    /// <summary>The object type: &quot;track&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackObject_type
    {
        [EnumMember(Value = "track")]
        #pragma warning disable CS1591
        Track,
        #pragma warning restore CS1591
    }
}
