// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Spotify.OpenApiClient.Models
{
    /// <summary>&quot;The object type: \&quot;track\&quot;.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrackObjectType
    {
        [EnumMember(Value = "track")]
        #pragma warning disable CS1591
        Track,
        #pragma warning restore CS1591
    }
}
